Bug zap
micahrye/CognitivePlayground pull request #8
Opened 2016-11-18 16:35 UTC by kateharwood

2016-11-19 23:59 UTC, micahrye requested changes

2016-11-19 23:59 UTC, micahrye commented on components/BugZap/BugZapGame.js
> +      splashAnimationIndex: [3,4,5],
Why are aren't you using the character animationIndex function? and animation stuff? ie. character.animationIndex('SPLASH').

2016-11-19 23:59 UTC, micahrye commented on components/BugZap/BugZapGame.js
> +      splashAnimationIndex: [3,4,5],
see MatchColor for example

2016-11-23 03:19 UTC, kateharwood commented on components/BugZap/BugZapGame.js
> +      splashAnimationIndex: [3,4,5],
changed

2016-11-23 19:40 UTC, micahrye commented
I merged animate with new media and master. Now merging this PR.

2016-11-23 19:40 UTC, merged